---
title       : Getting to know your Body Mass Index 
subtitle    : Course Project Presentation
author      : Alfredo Hung
job         : Developing Data Products
framework   : io2012       # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : zenburn     # {tomorrow
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## How to run Slidify
0. setwd("C:/Users/alfredohung/Desktop/Data Science/9. Developing Data Products/Project/Slidify/presentation_slidify")
1. library(devtools)
2. library(slidify)
3. slidify("index.Rmd")
4. browseURL("index.html")
5. publish_github(alfredohung, https://github.com/alfredohung/alfredohung/dataproducts)

--- .class #id 

## Introduction

- In this project a Shiny web application is developed to calculate the Body Mass Index (BMI) of an adult given his/her weight and height

- This app is intended to be used only in English units so the measures of height should be in feet and inches, and weight in pounds

- The app returns also a (1) BMI classification according to the National Institute of Health of the US Dept. of Health & Human Services and (2) the ideal body weight using the Devine formula

- The BMI tool is deployed on Rstudio's shiny servers: https://alfredohung.shinyapps.io/CourseProject/

- The app's files, ui.R and server.R, are in github (copy & paste): https://github.com/alfredohung/dataproducts.git

---

## What is Body Mass Index?

- Body mass index is a measure of body fat based on weight in relation to  height that applies to most adult men and women aged 20 and over 
- The higher the BMI, the higher the risk for certain diseases such as heart disease, high blood pressure, type 2 diabetes, gallstones, breathing problems, and certain cancers
- The same formula for BMI is used for both men and women : $BMI = weight * 703 / height^{2}$
- BMI has a few limits:
    + It may overestimate body fat in athletes and others who have a muscular build
    + It may underestimate body fat in pregnant women, older persons and others who have lost muscle

---

## BMI Classification and Ideal Body Weight 

- BMI is a quick, easy-to-use tool to assess overweight and obesity and help individuals self-manage their weight and eating habits
- Overweight (BMI of 25 to 29.9) and Obesity (BMI greater than or equal to 30) are defined as BMI exceeding the 85th and 95th centiles of the US CDC 2000 reference
- Being overweight or obese with at least two health risk factors increases the risk of developing diseases associated with obesity
- The estimation of the Ideal Body Weight (IBW) allows for estimation of drug clearances in obese patients since the metabolism of certain drugs relates more to IBW than total body weight. The most common estimation is by the Devine formula
- The Devine formula for Ideal Body Weight (IBW) differs by gender : $IBW.male = 110.23+5.07*(height-60)$, $IBW.female = 100.31+5.07*(height-60)$


---

## How the BMI app works (demo)

```{r demo, echo=T}
# Initial values in lbs, inches
weight = 172; height = 71 
# Calculate BMI
bmi <- round(703 * weight / height^2, 2); bmi  
bmi.result <- function(bmi) { # Get BMI classification
        if (bmi < 18.5) {"Underweight"
        } else if (bmi >= 18.5 & bmi <= 24.9) {"Normal Weight"
        } else if (bmi >= 25 & bmi <= 29.9) {"Overweight"
        } else if (bmi >= 30 & bmi <= 39.9) {"Obesity"
        } else if (bmi > 40) {"Extreme Obesity"}
}; bmi.result(bmi)
```
---

## Question
What is your BMI?

1.20
2._24_
3.25
4.32
*** .hint Use the calculator
*** .explanation it's your height divided by your weight
---
